### ISSUE TITLE
sorry, just about the demo recorder tools

### ISSUE THREAD

**Issue by allen7u** [itsbrex/ChatGPT-Cookies-Plus#5]
I know this is off topic, but your demo is so cool. so what tool did you use, is there any tutorial for this kind of camera operation?

**Comment by itsbrex** [comment]
Sorry for the suuuper late response on this, but thank you! The app is called [Screen Studio](https://www.screen.studio/)!

@allen7u

**Comment by allen7u** [comment]
> Sorry for the suuuper late response on this, but thank you!

Sorry for the suuuper late response too, Thank you! Are there any alternatives on Windows that are close to it?
